#!/bin/sh
#说明
show_usage="args: [-c comment, -b branch, -d(delete)]"
comment=""
branch=""
delete=false
args=('-c', '-comment', '-b', '-branch', '-d', '-delete')
while [[ -n "$1" ]]
do
        case "$1" in
                -c|-comment) if [[ "${args[@]}" =~ $2 || -z "$2" ]];then
								echo 'the -c require value'
								exit 1
							else
								comment=$2; shift 2
							fi;;
                -b|-branch) if [[ "${args[@]}" =~ $2 || -z "$2" ]];then
								echo 'the -b require value'
								exit 1
							else
								branch=$2; shift 2
							fi;;
                -d|-delete) if [[ "${args[@]}" =~ $3 ]];then
								echo 'the -c require value'
								exit 1
							else
								delete=true; shift 2
							fi;;
                --) echo 'a';shift 1;break ;;
                *) echo 'b';shift 1;echo $show_usage;break ;;
        esac
done

if [[ -z $comment || -z $branch || -z $delete ]]; then
        echo "comment: $comment , branch: $branch , delete: $delete"
        exit 0
fi