#!/bin/bash
export LC_ALL=en_US.UTF-8

read oldrev $newrev ref
if [[ $(pwd) =~ ([a-z]+)\.git ]]
then
	project=${BASH_REMATCH[1]}
else
	echo '项目丢失'
	exit
fi
commit_dir="/data/merge/"
svn_dir="/data/merge/$project"
git_dir="/data/git_merge/$project"
br=$(echo $ref| cut -d \/ -f 3)
strs="Committed"
unset GIT_DIR
if [ $br = "pro" -o $br = "test" -o $br = "dev" -o $br = "release" ];then

	cd $svn_dir
	sudo svn up 2>&1 >/dev/null

	cd $git_dir
	git checkout $br >/dev/null 2>&1
	sudo chown -R git:git /data/git_merge/*
	git pull origin $br >/dev/null 2>&1
	sleep 3
	rsync -avz --delete $git_dir/* --exclude '.git' $svn_dir/$br/ >/dev/null 2>&1
	sleep 3

	echo "推送分支: " $br
	git log -m -1  --name-status --pretty=format:"本次hash: %H%n合并hash: %p%n提交帐号: %cn<%ce>%n提交时间: %cd%n提交信息: %s%n变更文件" --date=format:"%F %T" $newrev

	name=$(git log -1 --pretty=format:%cn $newrev)
	echo "svn信息"
	cd $commit_dir
	sudo svn add $svn_dir/$br --force
	svn_commit=$(sudo svn commit -m "x" $svn_dir/$br)
	#echo $svn_commit|sed "s@Sending@\nSending@g"|sed "s@Adding@\nAdding@g"
	echo -e "$svn_commit"
	select=$(echo $svn_commit|grep $strs)

	if [[ x"$select" == x"" ]];then
        	echo "更新服务器失败，请联系管理员"
	else
		echo "更新服务器成功!"
	fi

fi
